Fix 2 multi box single frame
mbari-media-management/cthulhu pull request #7
Opened 2021-03-19 23:20 UTC by carueda

Hey @hohonuuli  I think I have fixed this, even for  small time window (like the 100ms we've been using lately).

Here's a video I just uploaded demonstrating this:  https://youtu.be/YSjQQAk3qlw

The key aspect for the here solution is to do one more call to the handler in the timer when the video has just been paused, in this case with whatever last time is reported from the video player.

Please test it on your side when convenient.

2021-03-20 00:40 UTC, hohonuuli commented
@carueda Thanks Carlos! I probably won't get to this until Monday but I'll review it then.

2021-03-20 17:56 UTC, carueda commented
I just repeated the exercise:  https://youtu.be/325z9oMP30k

In particular, this shows the expected yellow color for the boxes just being drawn/finalized.  In the previous video taken yesterday those boxes were always white for some reason (... probably because of a slower vpn connection(?)).

2021-03-25 21:26 UTC, hohonuuli requested changes
@carueda Looks good. My only major comment is to comment out all the logging stuff. I'm concerned about having it in a time-sensitive loop.

2021-03-25 21:26 UTC, hohonuuli commented on src/main/java/org/mbari/cthulhu/ui/player/MediaPlayerTimer.java
> +                    final long currSysMillis = System.currentTimeMillis();
I did a little research to see tradeoffs between `currentTimeMillis()` and `nanoTime()`. The tl;dr is that the performance is comparible. So currentTimeMillis() is AOK to use here. Good write up on this at <http://pzemtsov.github.io/2017/07/23/the-slow-currenttimemillis.html>

2021-03-25 21:26 UTC, hohonuuli commented on src/main/java/org/mbari/cthulhu/ui/player/MediaPlayerTimer.java
> +                        onTick.accept(newMpMillis);
Note to myself: This is the major change here ... updating the `Consumer<Long> onTick` when paused.

2021-03-25 21:26 UTC, hohonuuli commented on src/main/java/org/mbari/cthulhu/ui/player/MediaPlayerTimer.java
> +                        log.trace("onTick: toCallTickMillis={} newMpMillis={} timeDirection={} (sysDiff={})",
I would comment out this entire logging block before accepting the PR. I'm concerned about the logging overhead in such a time-sensitive location.

2021-03-25 21:26 UTC, hohonuuli commented on src/main/java/org/mbari/cthulhu/ui/player/MediaPlayerTimer.java
> +                        log.trace("onTick: media just paused. Calling handler with newMpMillis={}", newMpMillis);
I would comment out these log calls before accepting the PR. I'm concerned about the logging overhead in such a time-sensitive location.

2021-03-25 21:26 UTC, hohonuuli commented on src/main/java/org/mbari/cthulhu/ui/player/MediaPlayerTimer.java
> +                    final long currSysMillis = System.currentTimeMillis();
I'm not sure if it makes a difference to call this ahead of time, like here, or at the call site (how it was in previous version). I'm guessing it's only on the order of a 100ns between this call site and its use later on. So nothing to do here, just noting it.

2021-03-25 22:41 UTC, carueda commented
Thanks for reviewing @hohonuuli .  No problem commenting out those conditioned `trace` logging statements, but note that they should be really pretty fast:

- the first one you indicate is explicitly guarded with `if (log.isTraceEnabled()) {`  so it won't go into the body if TRACE is not enabled
- the others involve arguments that, although do get evaluated regardless on logging level, all of them are direct variables already computed so it should also be super fast.

However, I agree and will comment those given the time sensitive section in which they are.  They are great for debugging, so rather easy to uncomment when needed.

I'll also look into the your other comment.

2021-03-25 22:56 UTC, carueda commented
Changes done.

2021-03-26 19:20 UTC, merged

2021-03-26 19:21 UTC, hohonuuli commented
Rebased into master and deleted this branch.